function [ xi,origin] = FindTwist( P )
%FindTwist Find the twist of a joint from a set of points generated by
%circular motion of the joint
%
%   [ xi,origin] = FindTwist( P )
%   P:      position of the point, 3xN     
%   xi:     joint twist, 6x1
%   origin: origin of the circle, 3x1

N=size(P,1);
%fit plane
b=-1*ones(N,1);
x_inv=(P'*P)\(P'*b);
x_inv=x_inv/norm(x_inv);
if(sum(x_inv)<0)
    x_inv=-x_inv;
end
w=x_inv;

%project points to fitted plane
z_new=x_inv;
x_new=cross(z_new,[1;1;1]);
x_new=x_new/norm(x_new);
y_new=cross(z_new,x_new);
C_new=[x_new,y_new,z_new];
P_reg=P*C_new;

%fit circle
Circle=CircleFitByKasa(P_reg(:,1:2));
origin_reg=[Circle(1);Circle(2);mean(P_reg(:,3))];
origin=C_new*origin_reg;
v=cross(origin,w);
xi=[w;v];
end